---
AWSTemplateFormatVersion: '2010-09-09'

Description: Lambda function 

Parameters:

  AccountId:
    Type: String
    Default: '106465311501'
    Description: AWS Account ID
    
  Msg:
    Type: String
    Default: 'Hello from APIGateway and Lambda!'
    Description: Message
    
  ApiName:
    Type: String
    Default: 'TestAPI'
    Description: API name

Resources:

  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Role: !GetAtt LambdaRole.Arn
      Handler: index.handler
      Code:
        ZipFile: !Sub |
          import json

          def lambda_handler(event, context):

              return {
                  "statusCode": 200,
                  "isBase64Encoded": False,
                  "body": json.dumps('${Msg}')
              }
      Description: Invoke a function during stack creation.
      TracingConfig:
        Mode: Active

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      Name: !Ref ApiName
      Description: API Name
      
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:execute-api:ap-southeast-2:${AccountId}:RestApi/*'
      
  RestApiStage:
    Type: AWS::ApiGateway::Stage
    DependsOn: ApiGatewayAccount
    Properties:
      StageName: default
      Description: Default Stage
      RestApiId: !Ref RestApi
      DeploymentId: !Ref DeploymentId
      Variables:
        Stack: Prod
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: *
          MetricsEnabled: 'false'
          DataTraceEnabled: 'false'

